// <auto-generated />
namespace Magazin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Shope : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Shope));
        
        string IMigrationMetadata.Id
        {
            get { return "202207171358020_Shope"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
