// <auto-generated />
namespace Magazin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Shop2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Shop2));
        
        string IMigrationMetadata.Id
        {
            get { return "202207171415008_Shop2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
